/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Principal;

//import javax.swing.ImageIcon;

import Utilerias.EstatusInfo;
import Utilerias.Numerosaletras;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author sistema
 */
public class Login extends javax.swing.JFrame {

    SplashScreen inicio;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        this.setSize(410, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Imagenes/SplashScreen/logo.png")).getImage());
        this.setTitle("ACCESO - SISTEMA FERRETERIA");
        
                //prueba de enunmeradores  
                        int ss;
                        String sss;
                        //ss=MenuPrincipal.ventas.value;
                        ss = EstatusInfo.MenuPrincipal.Ventas.ordinal();
                        ss = EstatusInfo.MenuPrincipal.Info.ordinal();
                        sss= Numerosaletras.converLetras(ss);
    }

    
    public Login(SplashScreen inicio) {
        this.inicio = inicio;
        setProgress(0, "Cargando Componentes del Sistema");
        initComponents();
        this.setSize(410, 500);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Recursos/Imagenes/SplashScreen/logo.png")).getImage());
        this.setTitle("ACCESO - SISTEMA ENRAMADA FERRETERIA");
        setProgress(20, "Conectandose a la Base de Datos...");
        setProgress(40, "Cargando Modulos..");
        setProgress(60, "Carga de Modulos Terminada");
        setProgress(80, "Cargando Interfaces..");
        setProgress(90, "Interfaces Cargadas");
        setProgress(100, "Bienvenido al Sistema");
        this.setLocationRelativeTo(null);
    }
    
    void setProgress(int percent, String information) {
        inicio.getJLabel().setText(information);
        inicio.getJProgressBar().setValue(percent);

        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(this, "No se pudo ejecutar la presentación");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(149, 76, 110, 14);
        jLabel1.getAccessibleContext().setAccessibleName("Nombre Usuario");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(149, 143, 100, 14);

        btnentrar.setText("Entrar");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar);
        btnentrar.setBounds(43, 233, 63, 23);

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(269, 233, 53, 23);

        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usuarioKeyReleased(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(140, 96, 132, 20);

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña);
        contraseña.setBounds(140, 168, 132, 20);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 420, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        String us = usuario.getText();
        String pas = contraseña.getText();
        if (us.equals("") || pas.equals("")) {
            JOptionPane.showMessageDialog(this, "Los campos son obligatorios", "Acceso", 0,
                    new ImageIcon(getClass().getResource("/imagenes/usuarios/info.png")));
        } else {
         //   Ingresa(us, pas);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btnentrarActionPerformed

     conecta cc = new conecta();
    Connection cn = cc.conexion();
    
     public void Ingresa(String id, String pas) {
        String dato = null;
        try {
            String sql = "SELECT nombre_us FROM usuarios WHERE nombre_us = '" + id + "'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.first()) {
                String sql1 = "SELECT pass FROM usuarios WHERE pass = '" + pas + "'";
                Statement st1 = cn.createStatement();
                ResultSet rs1 = st1.executeQuery(sql1);
                if (rs1.first()) {
                    String sql2 = "SELECT tipo_us FROM usuarios WHERE nombre_us = '" + id + "'"
                            + " and pass = '" + pas + "'";
                    Statement st2 = cn.createStatement();
                    ResultSet rs2 = st2.executeQuery(sql2);
                    while (rs2.next()) {
                        dato = rs2.getString(1);
                    }

                    if (dato.equals("ADMINISTRADOR")) {

                        String sql3 = "SELECT nombre_us FROM usuarios WHERE nombre_us = '" + id + "'";
                        Statement st3 = cn.createStatement();
                        ResultSet rs3 = st3.executeQuery(sql3);
                        while (rs3.next()) {
                            dato = rs3.getString(1);
                        }
                        dispose();
                        //MenuPrincipalAd mp = new MenuPrincipalAd();
                        JOptionPane.showMessageDialog(this, "BIENVENIDO A SIENSA " + dato, "Administrador", 0,
                                new ImageIcon(getClass().getResource("/imagenes/principal/adm.png")));
                        //mp.userConect.setText(dato);
                        //mp.setVisible(true);

                    } else {

                        String sql3 = "SELECT nombre_us FROM usuarios WHERE nombre_us = '" + id + "'";
                        Statement st3 = cn.createStatement();
                        ResultSet rs3 = st3.executeQuery(sql3);
                        while (rs3.next()) {
                            dato = rs3.getString(1);
                        }
                        dispose();
                                                
                        
                        
                      
                        
                        
                        //MenuPrincipalNor mp = new MenuPrincipalNor();
                        JOptionPane.showMessageDialog(this, "BIENVENIDO A SIENSA " + dato, "Normal", 0,
                                new ImageIcon(getClass().getResource("/imagenes/principal/norm.png")));
                        //mp.userConect.setText(dato);
                        //mp.setVisible(true);

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Acceso", 0,
                            new ImageIcon(getClass().getResource("/imagenes/principal/passLogin.png")));
                    this.contraseña.setText("");
                    this.usuario.transferFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe éste usuario.", "Acceso", 0,
                        new ImageIcon(getClass().getResource("/imagenes/principal/userLogin.png")));
                this.usuario.setText("");
                this.jLabel1.transferFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     
    
    
    private void usuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyReleased
        usuario.setText(usuario.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioKeyReleased

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
